# Generated by Django 5.1.3 on 2024-11-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='topic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
